### ISSUE TITLE
somethingID becomes something_i_d

### ISSUE THREAD

**Issue by geoffatsource** [bendrucker/snakecase-keys#47] opened 2021-04-28 23:23 UTC
Perhaps there should be an option to only split when there's a case change instead of on every capital letter

**Comment by bendrucker** [comment] 2021-04-29 00:00
I'm not eager to add an option here or significantly hurt performance. Happy to consider an alternative regex-based case library though. `snake-case` handles this:

https://github.com/blakeembrey/change-case/blob/5af7f9535bd5a5b609954a6b1765fa90a97698b7/packages/no-case/src/index.ts#L10-L11
https://runkit.com/bendrucker/6089f68918694e001b73bb6d

**Comment by bendrucker** [comment] 2021-04-29 00:10
Fixed in dc160e715bfe45d0b21c3a622fd21df5354e7bc6

**Closed by bendrucker** 2021-04-29 00:10 UTC

**Comment by geoffatsource** [comment] 2021-04-29 16:37
👍

**Comment by grzegorz-s** [comment] 2021-05-26 13:16
I know this issue is closed, but I just stepped into one potential regression with combination of usage other of your lib @bendrucker 

Background context
I'm using `camelcaseKeys` to transform data that comes from API, and before sending back (parameters or req body) I'm doing transformation with `snakecaseKeys`

```js
camelcaseKeys({ any_key_with_a_e: "camelCase" })
// returns anyKeyWithAE
```

and then back  version `4.0.1` 
```js
snakecaseKeys({anyKeyWithAE: 'snakecaseKeys'})
// returns any_key_with_a_e
```

so it matches with  `camelcaseKeys` transformation

with version `4.0.2` output will be `any_key_with_ae` -> no match and
```js
camelcaseKeys({any_key_with_ae: ''})
// returns anyKeyWithAe
```

Would you have any idea on how to keep same, consistent transformations? 🤔

**Comment by bendrucker** [comment] 2021-05-26 16:34
Open a new issue. Not sure there's going to be a way to handle this without adding opt-in options. The new behavior is more correct but I can see why you'd want to opt out in the case you're dealing with.

**Comment by ebylund** [comment] 2021-07-16 19:41
Tried updating to version 4, and i am running into this same issue. This seems like it would definitely be a breaking change. I am currently in a situation where I cannot upgrade because I cannot change the source of the keys I am converting to snake case. If I create a new issue with the potential to add in an opt-in option here? Happy to help with the PR.
